Ajit_Bakery/Models/TransferToDispatch.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Ajit_Bakery.Models
{
    public class TransferToDispatch
    {
        [Display(Name = "Sr.No")]
        public int Id { get; set; }
        [Display(Name = "Outlet Name")]
        public string Outlet_Name { get; set; }
        [Display(Name = "Box.No")]
        public string Box_No { get; set; }
        [Display(Name = "Product Name")]
        public string Product_Name { get; set; }
        [Display(Name = "Qty")]
        public int Qty { get; set; }
        [Display(Name = "Total Net.Wg.")]
        public double TotalNetWg { get; set; }
        [Display(Name = "Uom")]
        public string TotalNetWg_Uom { get; set; }
        [Display(Name = "Production.Dt")]
        public string Production_Dt { get; set; }
        [Display(Name = "Exp.Dt")]
        public string Exp_Dt { get; set; }
        [Display(Name = "Production Id")]
        public string Production_Id { get; set; }
        [Display(Name = "DispatchReady Flag")]
        public int? DispatchReady_Flag { get; set; } = 0;
        [Display(Name = "Packaging Date.")]
        public string? Packaging_Date { get; set; }
        [Display(Name = "Packaging Time.")]
        public string? Packaging_Time { get; set; }
        [Display(Name = "Reciept Id.")]
        public string? Reciept_Id { get; set; }
        public int? Dispatch_Flag { get; set; } = 0;
        public string? DispatchReady_Date { get; set; }
        public string? DispatchReady_Time { get; set; }
        public string? DCNo { get; set; }

        [NotMapped]
        public string Status { get; set; }

    }
}

Ajit_Bakery/Controllers/TransferToDispatchesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Ajit_Bakery.Data;
using Ajit_Bakery.Models;
using System.Drawing.Printing;
using System.Globalization;
using ZXing.OneD;
using AspNetCoreHero.ToastNotification.Notyf;
using Microsoft.AspNetCore.Hosting;
using System.Configuration;
using iTextSharp.text.pdf;
using iText.Html2pdf;
using iText.Html2pdf.Resolver.Font;
using iText.Layout.Font;
using Font = System.Drawing.Font;
using DocumentFormat.OpenXml.Office2016.Drawing.ChartDrawing;
using iText.Kernel.Font;
//using iText.IO.Font;
using PdfFont = iText.Kernel.Font.PdfFont;
using System.Runtime.InteropServices;
using Microsoft.AspNetCore.Authorization;
using System.Security.Claims;
using static System.Runtime.InteropServices.JavaScript.JSType;

namespace Ajit_Bakery.Controllers
{
    [Authorize]
    public class TransferToDispatchesController : Controller
    {
        private readonly DataDBContext _context;
        private readonly IConfiguration _configuration;
        private IWebHostEnvironment _webHostEnvironment;
        public TransferToDispatchesController(DataDBContext context, IWebHostEnvironment webHostEnvironment, IConfiguration configuration)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
            _configuration = configuration;
        }
        public class RepackingRequest
        {
            //Production_Id: Production_Id, DCNo: DCNo, Box_No: Box_No, Reciept_Id: Reciept_Id   
            public string Production_Id { get; set; }
            public string DCNo { get; set; }
            public string Box_No { get; set; }
            public string Reciept_Id { get; set; }
        }

        //[HttpPost]

        //public IActionResult GenerateDCPdf([FromBody] RepackingRequest request)
        //{
        //    try
        //    {
        //        var path = _configuration["AppSettings:TakePath"];

        //        //logo
        //        string imagePath = Path.Combine(path, "img", "logo.png");
        //        if (!System.IO.File.Exists(imagePath))
        //        {
        //            return BadRequest(new { error = "Image file not found at path: " + imagePath });
        //        }
        //        byte[] imageBytes = System.IO.File.ReadAllBytes(imagePath);
        //        string logoImgTag = Convert.ToBase64String(imageBytes);
        //        //end

        //        //signatur
        //        string imagePath1 = Path.Combine(path, "img", "sign.png");
        //        if (!System.IO.File.Exists(imagePath1))
        //        {
        //            return BadRequest(new { error = "Image file not found at path: " + imagePath1 });
        //        }

        //        byte[] imageBytes1 = System.IO.File.ReadAllBytes(imagePath1);
        //        string signatureImgTag = Convert.ToBase64String(imageBytes1);
        //        //end


        //        string fontPath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Fonts", "calibri-bold.ttf");
        //        PdfFont font = PdfFontFactory.CreateFont(fontPath, PdfEncodings.IDENTITY_H);
        //        var address = "";
        //        var CUSTOMER_NAME = "";
        //        var CONTACT_PERSON = "";
        //        var newmail = "";
        //        var CONTACT_MOBILE = "";
        //        var REMARKS = "";

        //        var ADD1 = "";
        //        var ADD2 = "";
        //        var ADD3 = "";
        //        string fullAddress = "";
        //        if (address.Length <= 50)
        //        {
        //            ADD1 = address;
        //            ADD2 = "";
        //            ADD3 = "";
        //        }
        //        else if (address.Length <= 100)
        //        {
        //            ADD1 = address.Substring(0, 50);
        //            ADD2 = address.Substring(50) + " .";
        //            ADD3 = "";
        //        }
        //        else
        //        {
        //            ADD1 = address.Substring(0, 50);
        //            ADD2 = address.Substring(50, 50);
        //            ADD3 = address.Substring(100) + " .";
        //        }

        //        var basicHeaderHtml = $@"
        //                <div style='display: flex; justify-content: space-between; align-items: flex-start;margin-right:8px;'>
        //                <div style='text-align: center;margin-right:8px;'>
        //                <div style='text-align: center;margin-right:8px;'><img src='data:image/png;base64,{logoImgTag}'  alt='Company Logo' style='width: 78px; height: 60px; margin: auto; display: block;' /></div>
        //                <h4 style='margin: 0;margin-top:0px; padding: 0; color: #2c758c; text-align: center; font-weight: bold;font-family: Calibri, Arial, sans-serif; '>AARKAY TECHNO</h4>
        //                <h4 style='margin: 0;margin-top:0px; padding: 1px 0;  color: #2c758c; text-align:center; font-weight: bold;font-family: Calibri, Arial, sans-serif; '>CONSULTANTS PVT.LTD.</h4>
        //                <p style='margin: 0;margin-top:0px; padding: 5px 0; background-color: #ec7c34; color: white; text-align:center; font-size: 8pt; font-weight: bold;width:200px;margin-right:8px;'>A TOTAL IT SOLUTIONS COMPANY</p>
        //                </div>
        //                <div style='text-align: right; font-size: 10pt; margin: 0;margin-top: 0px; padding: 0; line-height: 1;'>
        //                <p style='margin: 0; padding: 0; line-height: 1;font-family: Calibri, Arial, sans-serif; '>First floor,1,Samarth Nagar(W),Ajni Square,Wardha Road,Nagpur-440015,India.</p>
        //                <p style='margin: 0; padding: 0; line-height: 1;font-family: Calibri, Arial, sans-serif; '>Tel: +91 (712) 2252443 / 2251696; Mobile: 9764440738, 9764440734.</p>
        //                <p style='margin: 0; padding: 0; line-height: 1;font-family: Calibri, Arial, sans-serif; '>GSTN: 27AABCA9111E1Z3; PAN: AABCA9111E</p>
        //                <p style='margin: 0; padding: 0; line-height: 1;font-family: Calibri, Arial, sans-serif; '>CIN: U30007MH1997PTC112414</p>
        //                <p style='margin: 0; padding: 0; line-height: 1;font-family: Calibri, Arial, sans-serif; '>URN: UDYAM-MH-20-0013989</p>
        //                <p style='margin: 0; padding: 0; line-height: 1;font-family: Calibri, Arial, sans-serif; '><a href='http://www.atcgroup.co.in'>www.atcgroup.co.in</a>, <a href='mailto:info@atcgroup.co.in'>info@atcgroup.co.in</a></p>
        //                <svg style=' margin-top: 15px; margin-bottom: 0px;' height='50' width='450'  xmlns='http://www.w3.org/2000/svg'>
        //                <line x1='590' y1='18' x2='60' y2='18' style='stroke:#2c758c;stroke-width:10' />
        //                <line x1='590' y1='21' x2='50' y2='21' style='stroke:#808080;stroke-width:4' />
        //                </svg>
        //                </div>
        //                </div>
        //                <div style='clear: both; text-align: center; margin-top: 0px;'>

        //                </div>";


        //        string htmlTemplate = $@"<!DOCTYPE html>
        //    <html lang='en'>
        //    <head>
        //        <meta charset='UTF-8'>
        //        <meta name='viewport' content='width=device-width, initial-scale=1.0'>
        //        <title>Delivery Challan</title>
        //        <style>
        //            @font-face {{
        //                        font-family: 'Calibri';
        //                        src: url('file://{fontPath}') format('truetype');}}
        //             body {{ font-family: Arial, sans-serif; padding: 15px; }}
        //            .header {{ text-align: center; }}
        //            .company-logo {{ width: 200px; }}
        //            .bordered-box {{ border: 1px solid black; padding: 5px; }}
        //            .highlight {{ font-weight: bold; color: #000; }}
        //            .table {{ width: 100%; border-collapse: collapse; margin-top: 3px; }}
        //            .table, .table th, .table td {{ border: 1px solid black; padding: 4px; text-align: center; }}
        //            .remarks {{ background-color: #f8f9fa; padding: 7px; font-weight: bold; }}
        //            .signature-section {{ margin-top: 40px; display: flex; justify-content: space-between; }}
        //            .signature {{ text-align: center; width: 30%; border-top: 1px solid black; padding-top: 5px; }}
        //        </style>
        //    </head>
        //    <body>
        //        <div class='header'>
        //                            {basicHeaderHtml}
        //                        </div>

        //        <div style='display: flex; justify-content: space-between; width: 100%; margin-bottom: 10px; margin-top:5px;'>
        //            <div style='flex: 1; text-align: left; font-weight: bold;'>
        //                Ref: <span class='bordered-box'>{request.Production_Id}</span>
        //            </div>
        //            <div style='flex: 1; text-align: right; font-weight: bold;'>
        //                Date: <span class='bordered-box'>{DateTime.Now:dd/MM/yyyy}</span>
        //            </div>
        //        </div>

        //        <h4 style='text-align:center; text-decoration:underline; font-weight:bold;'>DELIVERY CHALLAN - SALE</h4>

        //        <div class='bordered-box'>
        //            <h3>To, <br><span class='highlight'>{CUSTOMER_NAME}</span></h3>
        //            <p>{ADD1},<br>{ADD2}<br>{ADD3}</p>
        //            <p><strong>Contact Person: </strong>{CONTACT_PERSON}</p>
        //            <p><strong>Mob: </strong>{CONTACT_MOBILE}</p>
        //            <p><strong>Email: </strong>{newmail}</p>
        //        </div>
        //         <table class='table'>
        //            <thead>

Ajit_Bakery/Views/TransferToDispatches/Delete.cshtml
@model Ajit_Bakery.Models.TransferToDispatch

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TransferToDispatch</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Outlet_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Outlet_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Box_No)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Box_No)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalNetWg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalNetWg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalNetWg_Uom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalNetWg_Uom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Production_Dt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Production_Dt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Exp_Dt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Exp_Dt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Production_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Production_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DispatchReady_Flag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DispatchReady_Flag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Packaging_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Packaging_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Packaging_Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Packaging_Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reciept_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reciept_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dispatch_Flag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dispatch_Flag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DispatchReady_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DispatchReady_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DispatchReady_Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DispatchReady_Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DCNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DCNo)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Ajit_Bakery/Views/TransferToDispatches/Details.cshtml
@model Ajit_Bakery.Models.TransferToDispatch

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>TransferToDispatch</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Outlet_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Outlet_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Box_No)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Box_No)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product_Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product_Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Qty)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Qty)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalNetWg)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalNetWg)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TotalNetWg_Uom)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TotalNetWg_Uom)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Production_Dt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Production_Dt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Exp_Dt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Exp_Dt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Production_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Production_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DispatchReady_Flag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DispatchReady_Flag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Packaging_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Packaging_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Packaging_Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Packaging_Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Reciept_Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Reciept_Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Dispatch_Flag)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Dispatch_Flag)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DispatchReady_Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DispatchReady_Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DispatchReady_Time)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DispatchReady_Time)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DCNo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DCNo)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Ajit_Bakery/Views/TransferToDispatches/Index.cshtml
@model IEnumerable<Ajit_Bakery.Models.Packaging>

@{
    ViewData["Title"] = "Index";

    string Depname = User.Claims.FirstOrDefault(a => a.Type == "UserDept").Value;
}

<div class="card">
    <div class="card-header bg-dark text-white py-2">
        <div class="d-flex align-items-baseline">
            <a asp-action="Index" asp-controller="Home" class="btn btn-link text-white"><i class="fa fa-arrow-left"></i></a>
            <h4 class="mx-auto text-white text-2xl font-semibold">  Transfer To Dispatch </h4>
            @if (Depname != "Dispatch")
            {
                <a asp-action="Create" asp-controller="TransferToDispatches" class="btn btn-success btn-sm text-white">
                    <i class="fas fa-plus-square"></i>  Transfer To Dispatch
                </a>
            }

        </div>
    </div>
    <div class="card-body mt-4">
        <div class="table table-responsive">
            <table id="SavePackaging" class="table table-striped table-bordered" style="width:100%">
                <thead class="thead-light">
                    <tr class="text-center small">
                        <th class="text-center">Sr.No.</th>
                        <th class="text-center">Production Id </th>
                        @* <th class="text-center">DC No. </th> *@
                        <th class="text-center">Outlet Name </th>
                        <th class="text-center">Box No.</th>
                        <th class="text-center">Receipt No.</th>
                        <th class="text-center">Product Name.</th>
                        <th class="text-center">Category</th>
                        <th class="text-center">Total Qty</th>
                        @* <th>DC Download</th> *@
                    </tr>
                </thead>
                <tbody class="small text-center">
                    @{
                        int counter = 1;
                    }
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td class="text-center">@counter</td>
                            <td style="font-weight:600;color:rebeccapurple">@Html.DisplayFor(modelItem => item.Production_Id)</td>
                            @* <td style="font-weight:600;color:cadetblue">@Html.DisplayFor(modelItem => item.DCNo)</td> *@
                            <td style="font-weight:600;color:chocolate">@Html.DisplayFor(modelItem => item.Outlet_Name)</td>
                            <td style="font-weight:600;color:green">@Html.DisplayFor(modelItem => item.Box_No)</td>
                            <td><span class="badge bg-primary">@Html.DisplayFor(modelItem => item.Reciept_Id)</span></td>
                            <td>@Html.DisplayFor(modelItem => item.Product_Name)</td>
                            <td>@Html.DisplayFor(modelItem => item.Category)</td>
                            <td style="text-align:center">@Html.DisplayFor(modelItem => item.Qty)</td>
                            @*   <td>
                                <button class="btn btn-warning btn-sm"
                                        onclick="GenerateDCPdf('@item.Production_Id', '@item.DCNo', '@item.Box_No', '@item.Reciept_Id')">
                                    <i class="fas fa-file-invoice"></i> DC
                                </button>
                            </td> *@
                        </tr>
                        counter++;
                    }
                </tbody>
            </table>

        </div>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    <script>
        function GenerateDCPdf(Production_Id, DCNo, Box_No, Reciept_Id) {
            // $('#loadingIndicator').show();
            console.log("GenerateDCPdf called with Sono:", Production_Id, "Id:", Reciept_Id);
            Swal.fire({ icon: 'warning', title: 'Warning', text: 'Functionality is not define !' });
            // $.ajax({
            //     url: '/TransferToDispatches/GenerateDCPdf',
            //     method: 'POST',
            //     contentType: 'application/json',
            //     data: JSON.stringify({ Production_Id: Production_Id, DCNo: DCNo, Box_No: Box_No, Reciept_Id: Reciept_Id }),
            //     xhrFields: { responseType: 'blob' }, // Handle binary files
            //     success: function (blob) {
            //         // $('#loadingIndicator').hide();
            //         console.log("blob: " + blob);
            //         var link = document.createElement('a');
            //         var url = window.URL.createObjectURL(blob);
            //         link.href = url;
            //         link.download = "DeliveryChallan.pdf";
            //         document.body.appendChild(link);
            //         link.click();
            //         document.body.removeChild(link);
            //         window.URL.revokeObjectURL(url);
            //     },
            //     error: function (xhr, status, error) {
            //         console.error("GenerateDCPdf Error:", error);
            //         // $('#loadingIndicator').hide();
            //         Swal.fire({ icon: 'error', title: 'Error', text: 'Failed to generate PDF.' });
            //     }
            // });
        }

        // $(document).ready(function () {
        //     $('#SavePackaging').DataTable({
        //         dom: 'Bfrtip', // Add button controls
        //         buttons: [
        //            {
        //                 extend: 'excel',
        //                 title: 'Packaging Report',
        //                 filename: function () {
        //                     return generateFilename('Packaging Report');
        //                 },
        //                 text: '<i class="fas fa-file-excel"></i> Export Excel',
        //                 className: 'dt-button btn btn-success',
        //                 exportOptions: {
        //                     columns: ':not(.noExport)' // Exclude columns with class 'noExport'
        //                 },
        //             },
        //             {
        //                 extend: 'pdf',
        //                 title: 'Packaging Report',
        //                 filename: function () {
        //                     return generateFilename('Packaging Report');
        //                 },
        //                 text: '<i class="fas fa-file-pdf"></i> Export PDF',
        //                 className: 'dt-button btn btn-danger',
        //                 pageSize: 'A4',
        //                 exportOptions: {
        //                     columns: ':not(.noExport)' // Exclude columns with class 'noExport'
        //                 },
        //                 customize: function (doc) {
        //                     // Centering the title
        //                     doc.styles.title = {
        //                         fontSize: 16,
        //                         bold: true,
        //                         alignment: 'center'
        //                     };

        //                     // Adjusting table width
        //                     doc.content[1].table.widths = Array(doc.content[1].table.body[0].length + 1).join('*').split('');

        //                     // Define columns to exclude from centering (0-based index)
        //                     let excludeColumns = []; // Example: Excluding 2nd and 4th columns

        //                     // Center align table content, except for excluded columns
        //                     let tableBody = doc.content[1].table.body;
        //                     tableBody.forEach(function (row, rowIndex) {
        //                         row.forEach(function (cell, colIndex) {
        //                             if (!excludeColumns.includes(colIndex)) {
        //                                 cell.alignment = 'center'; // Center align text in all cells except excluded columns
        //                             }
        //                         });
        //                     });
        //                 }

        //             },

        //         ],
        //         info: false, ordering: false,
        //     });
        // });
        $(document).ready(function () {
            $('#SavePackaging').DataTable({
                dom: 'Bfrtip', // Add button controls
                buttons: [
                    {
                        extend: 'excel',
                        title: 'Packaging Report',
                        filename: function () {
                            return generateFilename('Packaging Report');
                        },
                        text: '<i class="fas fa-file-excel"></i> Export Excel',
                        className: 'dt-button btn btn-success',
                        exportOptions: {
                            columns: ':not(:last-child)' // Exclude the last column
                        },
                    },
                    {
                        extend: 'pdf',
                        title: 'Packaging Report',
                        filename: function () {
                            return generateFilename('Packaging Report');
                        },
                        text: '<i class="fas fa-file-pdf"></i> Export PDF',
                        className: 'dt-button btn btn-danger',
                        pageSize: 'A4',
                        exportOptions: {
                            columns: ':not(:last-child)' // Exclude the last column
                        },
                        customize: function (doc) {
                            // Centering the title
                            doc.styles.title = {
                                fontSize: 16,
                                bold: true,
                                alignment: 'center'
                            };

                            // Adjusting table width
                            doc.content[1].table.widths = Array(doc.content[1].table.body[0].length + 1).join('*').split('');

                            // Center align table content
                            let tableBody = doc.content[1].table.body;
                            tableBody.forEach(function (row) {
                                row.forEach(function (cell) {
                                    cell.alignment = 'center'; // Center align text in all cells
                                });
                            });
                        }
                    }
                ],
                info: false,
                ordering: false,
            });
        });


        function generateFilename(baseName) {
            const now = new Date();
            const date = now.toISOString().slice(0, 10).replace(/-/g, '_'); // Format: YYYY_MM_DD
            return `${baseName}_${date}`;
        }
    </script>
}